Init axios & api service
htmlacademy-vue/231328-pizza-1 pull request #7
Opened 2022-06-06 18:33 UTC by Qleager

2022-06-06 20:55 UTC, enotke commented on src/frontend/src/store/modules/builder.store.js
> +    async query({ commit }) {
Тебе нужно подождать завершения экшена query или сделать какие-нибудь заглушки с дефолтными значениями. Можно например лоадер добавить и пока страница полностью не загрузится вообще ничего не показывать.

2022-08-03 22:21 UTC, enotke requested changes

2022-08-03 22:21 UTC, enotke commented on src/frontend/src/common/mixins/validator.js
> +  isNotEmpty: {
А в чем разница между isNotEmpty и required?

2022-08-03 22:21 UTC, enotke commented on src/frontend/src/services/api.service.js
> +export class ReadOnlyApiService {
Вообще принято писать каждый класс в отдельном файле

2022-08-03 22:21 UTC, enotke commented on src/frontend/src/services/api.service.js
> +    this.#resource = resource;
Это поле уже есть в ReadOnlyApiService

2022-08-03 22:21 UTC, enotke commented on src/frontend/src/store/index.js
> +      return get(rootState, path);
Не самое лучшее решение конечно. Приходится постоянно помнить названия полей + в случае чего можно долго искать опечатку

2022-08-03 22:21 UTC, enotke commented on src/frontend/src/store/modules/auth.store.js
> +      dispatch("getMe");
Тут бы тоже await не помешал

2022-08-03 22:21 UTC, enotke commented on src/frontend/src/views/Index.vue
> +        <h1 class="title title--big" @click="tlt()">Конструктор пиццы</h1>
Нет такого метода

2022-08-03 22:21 UTC, enotke commented on src/frontend/src/views/Login.vue
> +          :required="true"
можно просто required написать

2022-08-03 22:21 UTC, enotke commented on src/frontend/src/views/Login.vue
> +    this.$refs.email.$refs.input.focus();
Не стоит обращаться к компонентам через рефы. Лучше уж сделать пропс focus и управлять состоянием через него

2022-08-04 08:03 UTC, qleager commented on src/frontend/src/services/api.service.js
> +    this.#resource = resource;
Все правильно, не понимаю в чем ошибка. Инициализируем же

2022-08-04 08:04 UTC, enotke commented on src/frontend/src/services/api.service.js
> +    this.#resource = resource;
Как таковой ошибки нет, но это поле уже есть в дочернем классе. Зачем его ещё раз присваивать?

2022-08-04 08:22 UTC, qleager commented on src/frontend/src/services/api.service.js
> +    this.#resource = resource;
Если убрать, this#resources будет undefined

2022-08-04 08:39 UTC, enotke commented on src/frontend/src/services/api.service.js
> +    this.#resource = resource;
Нужно сделать геттер для приватного поля

2022-08-04 08:39 UTC, merged